const SITE_URL = 'https://sfe.aedanl.com';

const PLAN_PAGES = [
  {
    slug: 'plan-1-overseas-repayment',
    kind: 'plan',
    plan: 'Plan 1',
    title: 'Plan 1 Overseas Student Loan Repayment',
    metaTitle: 'Plan 1 Overseas Student Loan Repayment Calculator',
    description: 'Learn how Plan 1 UK student loan repayments work when you live overseas, including thresholds, the 9% repayment rate, and how to estimate your monthly payment.',
    intro: 'Plan 1 overseas repayments use country-specific earnings thresholds. If your converted annual income is above the threshold for the country where you live, Student Finance expects 9% of the amount above that threshold.',
  },
  {
    slug: 'plan-2-overseas-repayment',
    kind: 'plan',
    plan: 'Plan 2',
    title: 'Plan 2 Overseas Student Loan Repayment',
    metaTitle: 'Plan 2 Overseas Student Loan Repayment Calculator',
    description: 'Check how Plan 2 student loan repayments are calculated for UK graduates living abroad, with overseas thresholds, exchange rates, and monthly repayment examples.',
    intro: 'Plan 2 repayments overseas follow the same 9% rate used in the UK, but the earnings threshold varies by country and tax year.',
  },
  {
    slug: 'plan-4-overseas-repayment',
    kind: 'plan',
    plan: 'Plan 4',
    title: 'Plan 4 Overseas Student Loan Repayment',
    metaTitle: 'Plan 4 Overseas Student Loan Repayment Calculator',
    description: 'Estimate Plan 4 student loan repayments while living abroad. See how overseas thresholds and local salary conversion affect Scottish student loan payments.',
    intro: 'Plan 4 applies to Scottish student loans. Overseas repayments are calculated after converting your salary to GBP and comparing it with the threshold for your country of residence.',
  },
  {
    slug: 'plan-5-overseas-repayment',
    kind: 'plan',
    plan: 'Plan 5',
    title: 'Plan 5 Overseas Student Loan Repayment',
    metaTitle: 'Plan 5 Overseas Student Loan Repayment Calculator',
    description: 'Understand Plan 5 overseas student loan repayments for UK graduates abroad, including the 9% repayment rate, country thresholds, and salary conversion.',
    intro: 'Plan 5 is the newer undergraduate repayment plan for England and Wales. Overseas repayments still use 9% of converted income above the relevant country threshold.',
  },
  {
    slug: 'postgraduate-loan-overseas-repayment',
    kind: 'plan',
    plan: 'Postgraduate Loan',
    title: 'Postgraduate Loan Overseas Repayment',
    metaTitle: 'Postgraduate Loan Overseas Repayment Calculator',
    description: 'Work out how Postgraduate Loan repayments are calculated overseas, including the 6% repayment rate, overseas earnings thresholds, and combined repayments.',
    intro: 'Postgraduate Loans use a 6% repayment rate above the overseas threshold. If you also have an undergraduate loan, both repayments can apply at the same time.',
  },
];

const COUNTRY_PAGES = [
  {
    slug: 'student-loan-overseas-repayment-germany',
    kind: 'country',
    country: 'Germany',
    currency: 'EUR',
    title: 'UK Student Loan Repayment While Living in Germany',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Germany',
    description: 'Estimate UK student loan repayments for graduates living in Germany. Convert your euro salary and compare it with Student Loans Company overseas thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-australia',
    kind: 'country',
    country: 'Australia',
    currency: 'AUD',
    title: 'UK Student Loan Repayment While Living in Australia',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Australia',
    description: 'Calculate UK student loan repayments for graduates living in Australia using overseas repayment thresholds, exchange rates, and plan-specific repayment rates.',
  },
  {
    slug: 'student-loan-overseas-repayment-canada',
    kind: 'country',
    country: 'Canada',
    currency: 'CAD',
    title: 'UK Student Loan Repayment While Living in Canada',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Canada',
    description: 'Estimate UK student loan repayments from Canada. See how local salary, exchange rates, and overseas Student Loans Company thresholds affect monthly payments.',
  },
  {
    slug: 'student-loan-overseas-repayment-usa',
    kind: 'country',
    country: 'United States of America',
    currency: 'USD',
    title: 'UK Student Loan Repayment While Living in the USA',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator USA',
    description: 'Estimate UK student loan repayments for graduates living in the United States. See how your dollar salary converts to GBP and how it compares to SLC overseas thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-new-zealand',
    kind: 'country',
    country: 'New Zealand',
    currency: 'NZD',
    title: 'UK Student Loan Repayment While Living in New Zealand',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator New Zealand',
    description: 'Calculate UK student loan repayments for graduates living in New Zealand. Convert your NZD salary and compare it with Student Loans Company overseas thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-uae',
    kind: 'country',
    country: 'United Arab Emirates',
    currency: 'AED',
    title: 'UK Student Loan Repayment While Living in the UAE',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator UAE',
    description: 'Estimate UK student loan repayments for graduates living in the United Arab Emirates. See how your AED salary converts and how overseas SLC thresholds apply.',
  },
  {
    slug: 'student-loan-overseas-repayment-france',
    kind: 'country',
    country: 'France',
    currency: 'EUR',
    title: 'UK Student Loan Repayment While Living in France',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator France',
    description: 'Estimate UK student loan repayments for graduates living in France. Convert your euro salary and compare it with the Student Loans Company overseas earnings thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-netherlands',
    kind: 'country',
    country: 'Netherlands',
    currency: 'EUR',
    title: 'UK Student Loan Repayment While Living in the Netherlands',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Netherlands',
    description: 'Calculate UK student loan repayments for graduates living in the Netherlands. See how your euro salary and overseas SLC thresholds determine your monthly payment.',
  },
  {
    slug: 'student-loan-overseas-repayment-ireland',
    kind: 'country',
    country: 'Ireland',
    currency: 'EUR',
    title: 'UK Student Loan Repayment While Living in Ireland',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Ireland',
    description: 'Estimate UK student loan repayments for graduates living in Ireland. Enter your gross salary in euros and see your estimated monthly SLC overseas repayment.',
  },
  {
    slug: 'student-loan-overseas-repayment-spain',
    kind: 'country',
    country: 'Spain',
    currency: 'EUR',
    title: 'UK Student Loan Repayment While Living in Spain',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Spain',
    description: 'Calculate UK student loan repayments for graduates living in Spain. Convert your euro salary and compare it with Student Loans Company overseas earnings thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-sweden',
    kind: 'country',
    country: 'Sweden',
    currency: 'SEK',
    title: 'UK Student Loan Repayment While Living in Sweden',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Sweden',
    description: 'Estimate UK student loan repayments for graduates living in Sweden. See how your Swedish krona salary converts to GBP and how overseas SLC thresholds apply.',
  },
  {
    slug: 'student-loan-overseas-repayment-switzerland',
    kind: 'country',
    country: 'Switzerland',
    currency: 'CHF',
    title: 'UK Student Loan Repayment While Living in Switzerland',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Switzerland',
    description: 'Calculate UK student loan repayments for graduates living in Switzerland. Convert your CHF salary and compare it with Student Loans Company overseas thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-singapore',
    kind: 'country',
    country: 'Singapore',
    currency: 'SGD',
    title: 'UK Student Loan Repayment While Living in Singapore',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Singapore',
    description: 'Estimate UK student loan repayments for graduates living in Singapore. See how your SGD salary converts to GBP and how overseas SLC earnings thresholds are applied.',
  },
  {
    slug: 'student-loan-overseas-repayment-japan',
    kind: 'country',
    country: 'Japan',
    currency: 'JPY',
    title: 'UK Student Loan Repayment While Living in Japan',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Japan',
    description: 'Calculate UK student loan repayments for graduates living in Japan. Convert your yen salary and compare it with Student Loans Company overseas earnings thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-south-africa',
    kind: 'country',
    country: 'South Africa',
    currency: 'ZAR',
    title: 'UK Student Loan Repayment While Living in South Africa',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator South Africa',
    description: 'Estimate UK student loan repayments for graduates living in South Africa. See how your rand salary converts to GBP and how overseas SLC thresholds affect your payment.',
  },
  {
    slug: 'student-loan-overseas-repayment-hong-kong',
    kind: 'country',
    country: 'Hong Kong',
    currency: 'HKD',
    title: 'UK Student Loan Repayment While Living in Hong Kong',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Hong Kong',
    description: 'Calculate UK student loan repayments for graduates living in Hong Kong. Convert your HKD salary and compare it with Student Loans Company overseas earnings thresholds.',
  },
  {
    slug: 'student-loan-overseas-repayment-norway',
    kind: 'country',
    country: 'Norway',
    currency: 'NOK',
    title: 'UK Student Loan Repayment While Living in Norway',
    metaTitle: 'UK Student Loan Overseas Repayment Calculator Norway',
    description: 'Estimate UK student loan repayments for graduates living in Norway. See how your Norwegian krone salary converts to GBP and how overseas SLC thresholds apply.',
  },
];

const SEO_PAGES = [...PLAN_PAGES, ...COUNTRY_PAGES];

function getSeoPage(slug) {
  return SEO_PAGES.find((page) => page.slug === slug) || null;
}

module.exports = {
  SITE_URL,
  PLAN_PAGES,
  COUNTRY_PAGES,
  SEO_PAGES,
  getSeoPage,
};
