services:
  student-loan-app:
    build: .
    container_name: sfe_web_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-webapp.rule=Host(`sfe.aedanl.com`)"
      - "traefik.http.services.route-webapp.loadbalancer.server.port=3000"
      - "traefik.http.routers.route-webapp.middlewares=homeass@file"

networks:
  traefik_default:
    external: true
