const getSymbolFromCurrency = require('currency-symbol-map');

// Maps gov.uk currency names (as they appear in the overseas threshold tables)
// to ISO 4217 codes. The package handles the symbol lookup from there.
// Note: gov.uk uses some inconsistent spacing (e.g. "Hong  Kong Dollar") —
// both variants are included where known.
const NAME_TO_ISO = {
  'Afghanis':                                   'AFN',
  'Algerian Dinar':                             'DZD',
  'Antillean Guilder':                          'ANG',
  'Antilles Guilder':                           'ANG',
  'Argentine Peso':                             'ARS',
  'Aruban Guilder':                             'AWG',
  'Australian Dollar':                          'AUD',
  'Azerbaijanian Manat':                        'AZN',
  'Bahamian Dollar':                            'BSD',
  'Bahrain Dinar':                              'BHD',
  'Barbados Dollar':                            'BBD',
  'Belarusian Ruble':                           'BYN',
  'Belizean Dollar':                            'BZD',
  'Bermudian Dollar':                           'BMD',
  'Bhutanese Ngultrum':                         'BTN',
  'Bolivar Fuerte':                             'VEF',
  'Boliviano':                                  'BOB',
  'British Pound':                              'GBP',
  'Brunei Dollar':                              'BND',
  'Bulgarian Lev':                              'BGN',
  'Burundi Franc':                              'BIF',
  'CFA Franc (BEAC)':                           'XAF',
  'CFA Franc (BCEAO)':                          'XOF',
  'CFP Franc':                                  'XPF',
  'Canadian Dollar':                            'CAD',
  'Cape Verde Escudo':                          'CVE',
  'Cayman Islands Dollar':                      'KYD',
  'Chilean Peso':                               'CLP',
  'Colombian Peso':                             'COP',
  'Comorian Franc':                             'KMF',
  'Congolese Franc':                            'CDF',
  'Convertible Marka':                          'BAM',
  'Costa Rican Colon':                          'CRC',
  'Cuban Peso':                                 'CUP',
  'Czech Koruna':                               'CZK',
  'Danish Krone':                               'DKK',
  'Djiboutian Franc':                           'DJF',
  'Dominican Peso':                             'DOP',
  'Dong':                                       'VND',
  'Dram':                                       'AMD',
  'East Caribbean Dollar':                      'XCD',
  'Egyptian Pound':                             'EGP',
  'Ethiopian Birr':                             'ETB',
  'Euro':                                       'EUR',
  'Falkland Pound':                             'FKP',
  'Fiji Dollar':                                'FJD',
  'Forint':                                     'HUF',
  'Ghanaian Cedi':                              'GHS',
  'Gold Cordoba':                               'NIO',
  'Gourde':                                     'HTG',
  'Guarani':                                    'PYG',
  'Guinean Franc':                              'GNF',
  'Guyanese Dollar':                            'GYD',
  'Hong Kong Dollar':                           'HKD',
  'Hryvnia':                                    'UAH',
  'Icelandic Krona':                            'ISK',
  'Indian Rupee':                               'INR',
  'Indonesian Rupiah':                          'IDR',
  'Iranian Rial':                               'IRR',
  'Iraqi Dinar':                                'IQD',
  'Jamaican Dollar':                            'JMD',
  'Jordanian Dinar':                            'JOD',
  'Kenya Schilling':                            'KES',
  'Kina':                                       'PGK',
  'Kip':                                        'LAK',
  'Kuwaiti Dinar':                              'KWD',
  'Kyat':                                       'MMK',
  'Kyrgyzstan Som':                             'KGS',
  'Lari':                                       'GEL',
  'Lebanese Pound':                             'LBP',
  'Leke':                                       'ALL',
  'Lempira':                                    'HNL',
  'Leone':                                      'SLE',
  'Liberian Dollar (US Dollar in use)':         'LRD',
  'Libyan Dinar':                               'LYD',
  'Lilangeni':                                  'SZL',
  'Loti':                                       'LSL',
  'Macedonian Denar':                           'MKD',
  'Malagasy Ariary':                            'MGA',
  'Malawi Kwacha':                              'MWK',
  'Mauritius Rupee':                            'MUR',
  'Metical':                                    'MZN',
  'Mexican Peso':                               'MXN',
  'Moldovan Leu':                               'MDL',
  'Moroccan Dirham':                            'MAD',
  'Nafka':                                      'ERN',
  'Namibian Dollar':                            'NAD',
  'Nepalese Rupee':                             'NPR',
  'New Israeli Shekel':                         'ILS',
  'New Sol':                                    'PEN',
  'New Zealand Dollar':                         'NZD',
  'Nigerian Naira':                             'NGN',
  'Norwegian Krone':                            'NOK',
  'Ouguiyas':                                   'MRU',
  "Pa'anga":                                    'TOP',
  'Pakistan Rupee':                             'PKR',
  'Patacas':                                    'MOP',
  'Philippine Peso':                            'PHP',
  'Pula':                                       'BWP',
  'Qatar Riyal':                                'QAR',
  'Rand':                                       'ZAR',
  'Rial Omani':                                 'OMR',
  'Riel':                                       'KHR',
  'Ringgit':                                    'MYR',
  'Romanian Leu':                               'RON',
  'Rufiyaa':                                    'MVR',
  'Russian Ruble':                              'RUB',
  'Rwanda Franc':                               'RWF',
  'Saint Helena Pound':                         'SHP',
  'Saudi Riyal':                                'SAR',
  'Serbian Dinar':                              'RSD',
  'Seychelles Rupee':                           'SCR',
  'Singapore Dollar':                           'SGD',
  'Solomon Islands Dollar':                     'SBD',
  'Somali Shilling':                            'SOS',
  'Somoni':                                     'TJS',
  'Sri Lankan Rupee':                           'LKR',
  'Sudanese Pound':                             'SDG',
  'Surinam Dollar':                             'SRD',
  'Swedish Krona':                              'SEK',
  'Swiss Franc':                                'CHF',
  'Syrian Pound':                               'SYP',
  'Taiwan Dollar':                              'TWD',
  'Taka':                                       'BDT',
  'Tala':                                       'WST',
  'Tanzanian Shilling':                         'TZS',
  'Tenge':                                      'KZT',
  'Thai Baht':                                  'THB',
  'Trinidad & Tobago Dollar':                   'TTD',
  'Tugrik':                                     'MNT',
  'Tunisian Dinar':                             'TND',
  'Turkish New Lira':                           'TRY',
  'Turkmenistan New Manat':                     'TMT',
  'U.A.E. Dirham':                              'AED',
  'U.S. Dollar':                                'USD',
  'Ugandan New Shilling':                       'UGX',
  'Uruguayan Peso':                             'UYU',
  'Uzbekistan Sum':                             'UZS',
  'Vatu':                                       'VUV',
  'Won Korea Dem. Rep':                         'KPW',
  'Won Korea Rep':                              'KRW',
  'Yemeni Rial':                                'YER',
  'Yen':                                        'JPY',
  'Yuan Renminbi':                              'CNY',
  'Zambian Kwacha':                             'ZMW',
  'Zimbabwean Gold':                            'ZWG',
  'Zloty':                                      'PLN',
};

// Symbols for ISO codes not yet in currency-symbol-map (e.g. very new currencies).
const CODE_OVERRIDES = {
  SLE: 'Le',   // Sierra Leonean Leone (2022 redenomination)
  ZWG: 'ZiG',  // Zimbabwean Gold (2024)
};

function currencySymbol(name) {
  // Collapse any run of whitespace/non-breaking spaces into a single space
  // so gov.uk typos like "Hong  Kong Dollar" still match the map.
  const normalised = name.replace(/[\s\u00A0]+/g, ' ').trim();
  const isoCode = NAME_TO_ISO[normalised];
  if (!isoCode) return name;
  return CODE_OVERRIDES[isoCode] || getSymbolFromCurrency(isoCode) || name;
}

module.exports = currencySymbol;
module.exports.NAME_TO_ISO = NAME_TO_ISO;
