server {
    listen 80;
    root /usr/share/nginx/html;

    location = /ads.txt {
        try_files /ads.txt =404;
    }

    location = /robots.txt {
        try_files /robots.txt =404;
    }

    location = / {
        try_files /index.html =404;
    }

    location / {
        return 301 https://sfe.aedanl.com$request_uri;
    }
}
